# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3346a6b88f0fd8ab3a9f107a6a403f57f01d8c7002807a4d299bf844ffbe9ba7ed95fa1508e7cdf0e8d10d9ecc5c783bf53f278b3d0dba2daa3507a0b60969fb

test:
  secret_key_base: 1c69d3aa5adddfaecaa22faa3ca4240a4f02bf15d3e6e68e4bd044482bee35534493f6ea307549b891e090b44e215e82acedeafdb5b202b6bf05d042b3b8f74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
